image: python:latest

# Some variables to make your CI DRY
variables:
  FILE: src/requirements.txt

before_script:
  #

stages:
  - build
  - exec
  - report

# This stage compiles the files
build:
  stage: build
  script:
    - make build
  artifacts:
    paths:
      - ./bin
      - ./output

exec:
  stage: exec
  script: 
    - apt-get -qq update && apt-get -qq install -y python
    - apt-get -qq update
    - apt-get -qq install -y python python-virtualenv python-pip libtk python-tk
    - virtualenv venv
    - . venv/bin/activate
    - make download
    - make exec
  artifacts:
    paths:
      # We need to publish our results so others can check them
      - ./input/results
      - ./output
  dependencies:
    - build


# This stage builds your report too
report:
  image: adnrv/texlive:latest
  stage: report
  script:
    - cd report
    - latexmk -f -pdf -pdflatex="pdflatex --shell-escape %O %S" report
    # move the file to the root folder
    - mv report.pdf ../
  artifacts:
    paths:
      - report.pdf
